defaults:
  - _self_
  - model: st_gcn

data:
  path: "data/raw" 
  batch_size: 32

project:
  name: "neuro_calc"
  seed: 42

training:
  epochs: 100
  lr: 1e-3
  batch_size: 32
  device: "cuda" # or "cpu"

classes: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "div", "equal", "minus", "mult", "plus"]